#!/bin/bash

. "${BASH_SOURCE%/*}/funcs.sh"

check_equal "$(ls -1 "$DIRNAME" | awk '{ if (NR > 1) printf ", "; printf "%s", $0 }')" \
    "dir.flac, obama.mp3, obama2.mp3, playlist.m3u, ra[ven].mp3, random.mp3, some.txt"
